import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ["var(--font-inter)", "-apple-system", "system-ui", "sans-serif"],
        sans: ["var(--font-inter)", "-apple-system", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
      },
      fontSize: {
        "2xs": ["0.75rem", { lineHeight: "1.25rem", letterSpacing: "-0.005em" }],
        xs: ["0.8125rem", { lineHeight: "1.375rem", letterSpacing: "-0.005em" }],
        sm: ["0.875rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em" }],
        base: ["1rem", { lineHeight: "1.625rem", letterSpacing: "-0.015em" }],
        lg: ["1.125rem", { lineHeight: "1.75rem", letterSpacing: "-0.02em" }],
        xl: ["1.375rem", { lineHeight: "1.875rem", letterSpacing: "-0.025em" }],
        "2xl": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.03em" }],
        "3xl": ["2.25rem", { lineHeight: "2.5rem", letterSpacing: "-0.035em" }],
        "4xl": ["2.875rem", { lineHeight: "3rem", letterSpacing: "-0.04em" }],
        "5xl": ["3.75rem", { lineHeight: "3.875rem", letterSpacing: "-0.045em" }],
        "6xl": ["4.75rem", { lineHeight: "4.875rem", letterSpacing: "-0.05em" }],
      },
      colors: {
        // Coinbase payments / coinbase.com canonical tokens
        bg: "#FFFFFF",
        "bg-dark": "#0A0B0D",
        "surface-soft": "#F5F6F8",
        "surface-strong": "#ECEEF1",
        "surface-card": "#FFFFFF",
        "surface-dark-elevated": "#141619",
        ink: "#0A0B0D",
        body: "#4A4E57",
        muted: "#6C7280",
        subtle: "#9CA3AF",
        brand: "#0052FF",
        "brand-active": "#003ECC",
        "brand-disabled": "#A8B8CC",
        "on-brand": "#FFFFFF",
        "on-dark": "#FFFFFF",
        "on-dark-soft": "#8E94A3",
        hairline: "#E2E4E8",
        "hairline-soft": "#EFEFF0",
        up: "#059669",
        down: "#DC2626",
        "accent-yellow": "#D97706",
        coinbase: {
          blue: "#0052FF",
          "blue-active": "#003ECC",
          "blue-dark": "#003ECC",
          "blue-disabled": "#A8B8CC",
          ink: "#0A0B0D",
          body: "#4A4E57",
          muted: "#6C7280",
          "muted-soft": "#9CA3AF",
          hairline: "#E2E4E8",
          "hairline-soft": "#EFEFF0",
          canvas: "#FFFFFF",
          "surface-soft": "#F5F6F8",
          "surface-strong": "#ECEEF1",
          dark: "#0A0B0D",
          "dark-elevated": "#141619",
          up: "#059669",
          down: "#DC2626",
          background: "#FFFFFF",
          surface: "#ECEEF1",
          border: "#E2E4E8",
          text: "#0A0B0D",
          "text-secondary": "#4A4E57",
        },
      },
      borderRadius: {
        pill: "999px",
        card: "1.25rem",
      },
      boxShadow: {
        card: "0 1px 3px rgba(0, 0, 0, 0.04), 0 4px 12px rgba(0, 0, 0, 0.02)",
        "card-md": "0 4px 6px rgba(0, 0, 0, 0.04), 0 10px 24px rgba(0, 0, 0, 0.06)",
        "card-lg": "0 10px 25px rgba(0, 0, 0, 0.08), 0 20px 48px rgba(0, 0, 0, 0.10)",
        "input-focus": "0 0 0 3px rgba(0, 82, 255, 0.12)",
      },
    },
  },
  plugins: [],
} satisfies Config;
